### ISSUE TITLE
Importing problem

### ISSUE THREAD

**Issue by techjs-chief** [samuveth/vue3-jazzicon#1]
I just installed the package and imported Jazzicon from the guide like this. 

`import Jazzicon from 'vue3-jazzicon/src/components'`

But I got an error.

`Jazzicon.vue:6 Uncaught SyntaxError: The requested module '/node_modules/color/index.js?v=d190ae2c' does not provide an export named 'default'`

**Comment by techjs-chief** [comment]
I solved the issue by creating a custom Jazzicon component, but I think you need to solve this issue so that they can use the package once they install it.
Thanks

**Comment by YusufcanY** [comment]
@samuveth solve this please, thanks

**Comment by samwhosung** [comment]
@YusufcanY are you using Vite?

**Comment by YusufcanY** [comment]
> @YusufcanY are you using Vite?

yes
these are my packages
```js
  "dependencies": {
    "vue": "^3.2.24",
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^2.0.1",
    "vite": "^2.9.1",
  }
```
i think its about the commonjs problem. The color package doesnt exporting package correctly.
Its need to be like below:
```js
export default Color;
```
Right now:
```js
module.exports = Color;
```

**Comment by samwhosung** [comment]
You can try adding this inside your `vite.config.ts` 

```js
optimizeDeps: {
    include: ['color'],
    // @ts-ignore
    allowNodeBuiltins: ['stream']
}
```

**Comment by YusufcanY** [comment]
```js
include: ['color']
```
is working but, mersenne-twister package giving the same error. I added to "include" array and its working right now. Thanks for the help.

**Comment by samwhosung** [comment]
@YusufcanY Okay, added it to the README. Thanks!
