### ISSUE TITLE
Incompatible with nuxt3

### ISSUE THREAD

**Issue by frangte** [samuveth/vue3-jazzicon#2]
Hi @samuveth thank you for creating this lib!

I started using your package to integrate with nuxt3, it works fine in dev mode but when I deploy to production I got a problem

![image](https://user-images.githubusercontent.com/19859575/169745174-7e555780-64eb-4a1d-8181-3e5982af624d.png)

I have config `vite` with this configuration

```
vite: {
    optimizeDeps: {
      include: ['mersenne-twister', 'color'],
    },
  },
```

Thanks

**Comment by samwhosung** [comment]
@frangte did you find any solution for this?

**Comment by frangte** [comment]
@samuveth not yet, but I rebuild my component base on `@metamask/jazzicon` and it works fine (after fork and support esm for `mersenne-twister` and `@metamask/jazzicon`)

**Comment by skix123** [comment]
Had the same issue and solved it in `nuxt.config.ts`

```js
export default defineNuxtConfig({
	alias: {
		'color': 'color/index.js',
		'mersenne-twister': 'mersenne-twister/src/mersenne-twister.js',
	},
});
```
